"""vincula transacciones con retenciones

Revision ID: 001163164f2d
Revises: 2cfb821a10d8
Create Date: 2026-09-25 20:29:39.618709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001163164f2d'
down_revision: Union[str, Sequence[str], None] = '2cfb821a10d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaccion', sa.Column('retencion_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_transaccion_retencion_id'), 'transaccion', ['retencion_id'], unique=False)
    op.create_foreign_key('fk_transaccion_retencion', 'transaccion', 'retencion', ['retencion_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transaccion_retencion', 'transaccion', type_='foreignkey')
    op.drop_index(op.f('ix_transaccion_retencion_id'), table_name='transaccion')
    op.drop_column('transaccion', 'retencion_id')
    # ### end Alembic commands ###
