"""modelo de lotes de tokens, transacciones y retenciones

Revision ID: 083d3b7ad411
Revises: c6192ba681e6
Create Date: 2026-09-24 20:02:25.197252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '083d3b7ad411'
down_revision: Union[str, Sequence[str], None] = 'c6192ba681e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lote_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo_saldo', sa.Enum('GRATIS', 'PAGADO', name='tipo_saldo'), nullable=False),
    sa.Column('origen', sa.Enum('ENTREGA_SEMANAL', 'VIDEO', 'COMPRA', 'PAGO_POR_ENSENAR', 'COMPENSACION', name='origen_lote'), nullable=False),
    sa.Column('cantidad_original', sa.Integer(), nullable=False),
    sa.Column('cantidad_restante', sa.Integer(), nullable=False),
    sa.Column('fecha_recepcion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.Enum('VIGENTE', 'AGOTADO', 'VENCIDO', name='estado_lote'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cantidad_restante <= cantidad_original', name='ck_lote_restante_no_supera_original'),
    sa.CheckConstraint('cantidad_restante >= 0', name='ck_lote_cantidad_no_negativa'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lote_tokens_fecha_vencimiento'), 'lote_tokens', ['fecha_vencimiento'], unique=False)
    op.create_index(op.f('ix_lote_tokens_usuario_id'), 'lote_tokens', ['usuario_id'], unique=False)
    op.create_table('retencion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('solicitud_id', sa.UUID(), nullable=True),
    sa.Column('sesion_id', sa.UUID(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVA', 'LIBERADA', 'REEMBOLSADA', name='estado_retencion'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_liberacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_resolucion', sa.String(length=120), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retencion_usuario_id'), 'retencion', ['usuario_id'], unique=False)
    op.create_table('transaccion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_origen_id', sa.UUID(), nullable=True),
    sa.Column('usuario_destino_id', sa.UUID(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('CONSUMO', 'ENTREGA', 'COMPRA', 'REEMBOLSO', 'COMPENSACION', name='tipo_transaccion'), nullable=False),
    sa.Column('sesion_id', sa.UUID(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('saldo_resultante', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lote_tokens.id'], ),
    sa.ForeignKeyConstraint(['usuario_destino_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['usuario_origen_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaccion_usuario_destino_id'), 'transaccion', ['usuario_destino_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaccion_usuario_destino_id'), table_name='transaccion')
    op.drop_table('transaccion')
    op.drop_index(op.f('ix_retencion_usuario_id'), table_name='retencion')
    op.drop_table('retencion')
    op.drop_index(op.f('ix_lote_tokens_usuario_id'), table_name='lote_tokens')
    op.drop_index(op.f('ix_lote_tokens_fecha_vencimiento'), table_name='lote_tokens')
    op.drop_table('lote_tokens')
    # ### end Alembic commands ###
