"""catalogo de temas

Revision ID: 2cfb821a10d8
Revises: 94fc7d1800f3
Create Date: 2026-09-25 13:35:06.986152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cfb821a10d8'
down_revision: Union[str, Sequence[str], None] = '94fc7d1800f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('tema_padre_id', sa.Integer(), nullable=True),
    sa.Column('nivel', sa.SmallInteger(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'inactivo', name='estado_tema'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(nivel = 1 AND tema_padre_id IS NULL) OR (nivel > 1 AND tema_padre_id IS NOT NULL)', name='ck_tema_padre_segun_nivel'),
    sa.CheckConstraint('nivel BETWEEN 1 AND 3', name='ck_tema_nivel_valido'),
    sa.ForeignKeyConstraint(['tema_padre_id'], ['tema.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tema_padre_id', 'nombre', name='uq_tema_nombre_por_padre')
    )
    op.create_index(op.f('ix_tema_tema_padre_id'), 'tema', ['tema_padre_id'], unique=False)
    op.create_index('uq_tema_raiz_nombre', 'tema', ['nombre'], unique=True, postgresql_where=sa.text('tema_padre_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_tema_raiz_nombre', table_name='tema', postgresql_where=sa.text('tema_padre_id IS NULL'))
    op.drop_index(op.f('ix_tema_tema_padre_id'), table_name='tema')
    op.drop_table('tema')
    op.execute("DROP TYPE IF EXISTS estado_tema")
    # ### end Alembic commands ###
