"""crear tabla usuario

Revision ID: 4c054da99869
Revises: 
Create Date: 2026-09-21 01:45:09.823268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c054da99869'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre_visible', sa.String(length=80), nullable=False),
    sa.Column('estado_cuenta', sa.Enum('pendiente_confirmacion', 'activa', 'suspendida', 'eliminada', name='estado_cuenta'), nullable=False),
    sa.Column('consentimiento_grabacion', sa.Boolean(), nullable=False),
    sa.Column('fecha_consentimiento_grabacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultima_conexion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_correo'), 'usuario', ['correo'], unique=True)
    op.create_index(op.f('ix_usuario_estado_cuenta'), 'usuario', ['estado_cuenta'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_estado_cuenta'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_correo'), table_name='usuario')
    op.drop_table('usuario')
    op.execute("DROP TYPE IF EXISTS estado_cuenta")
    # ### end Alembic commands ###
