"""perfil publico

Revision ID: 7072acf2e577
Revises: dba5bf2b746e
Create Date: 2026-09-29 14:32:19.173489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7072acf2e577'
down_revision: Union[str, Sequence[str], None] = 'dba5bf2b746e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfil_publico',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('biografia', sa.String(length=500), nullable=True),
    sa.Column('enlace_personalizado', sa.String(length=30), nullable=True),
    sa.Column('reputacion_promedio', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('total_evaluaciones', sa.Integer(), nullable=False),
    sa.Column('consultas_completadas', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("enlace_personalizado ~ '^[a-z0-9_-]{3,30}$'", name='ck_perfil_enlace_formato'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_index(op.f('ix_perfil_publico_enlace_personalizado'), 'perfil_publico', ['enlace_personalizado'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_perfil_publico_enlace_personalizado'), table_name='perfil_publico')
    op.drop_table('perfil_publico')
    # ### end Alembic commands ###
