"""feat(identidad): crea tabla verificaciones_identidad

Revision ID: 776cd386d911
Revises: 4c054da99869
Create Date: 2026-09-22 20:35:41.398958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '776cd386d911'
down_revision: Union[str, Sequence[str], None] = '4c054da99869'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verificaciones_identidad',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=50), nullable=False),
    sa.Column('numero_documento', sa.String(length=50), nullable=False),
    sa.Column('url_foto_documento', sa.String(length=255), nullable=False),
    sa.Column('url_foto_rostro', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'APROBADA', 'RECHAZADA', name='estadoverificacion'), nullable=False),
    sa.Column('notas_revision', sa.Text(), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_resolucion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verificaciones_identidad')
    # ### end Alembic commands ###
