"""habilidades ofrecidas

Revision ID: dba5bf2b746e
Revises: 2cfb821a10d8
Create Date: 2026-09-26 22:47:52.579282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba5bf2b746e'
down_revision: Union[str, Sequence[str], None] = '2cfb821a10d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habilidad_ofrecida',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tema_id', sa.Integer(), nullable=False),
    sa.Column('precio_por_bloque', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('publicada', 'pausada', name='estado_habilidad'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('precio_por_bloque > 0', name='ck_habilidad_precio_positivo'),
    sa.ForeignKeyConstraint(['tema_id'], ['tema.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'tema_id', name='uq_habilidad_usuario_tema')
    )
    op.create_index(op.f('ix_habilidad_ofrecida_tema_id'), 'habilidad_ofrecida', ['tema_id'], unique=False)
    op.create_index(op.f('ix_habilidad_ofrecida_usuario_id'), 'habilidad_ofrecida', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_habilidad_ofrecida_usuario_id'), table_name='habilidad_ofrecida')
    op.drop_index(op.f('ix_habilidad_ofrecida_tema_id'), table_name='habilidad_ofrecida')
    op.drop_table('habilidad_ofrecida')
    op.execute("DROP TYPE IF EXISTS estado_habilidad")
    # ### end Alembic commands ###
