"""tabla de verificacion de identidad

Revision ID: fb0cdee40569
Revises: c6192ba681e6
Create Date: 2026-09-24 22:38:23.386930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb0cdee40569'
down_revision: Union[str, Sequence[str], None] = 'c6192ba681e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parametro_sistema',
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('valor', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('nombre')
    )
    op.create_table('verificacion_identidad',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('resultado', sa.Enum('aprobado', 'rechazado', name='resultado_verificacion'), nullable=False),
    sa.Column('nivel_confianza', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('hash_documento', sa.String(length=64), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verificacion_identidad_usuario_id'), 'verificacion_identidad', ['usuario_id'], unique=False)
    op.create_index('uq_verificacion_documento_aprobado', 'verificacion_identidad', ['hash_documento'], unique=True, postgresql_where=sa.text("resultado = 'aprobado'"))
    op.drop_table('verificaciones_identidad')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verificaciones_identidad',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tipo_documento', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('numero_documento', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('url_foto_documento', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('url_foto_rostro', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('estado', postgresql.ENUM('PENDIENTE', 'APROBADA', 'RECHAZADA', name='estadoverificacion'), autoincrement=False, nullable=False),
    sa.Column('notas_revision', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fecha_solicitud', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('fecha_resolucion', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('verificaciones_identidad_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('verificaciones_identidad_pkey')),
    sa.UniqueConstraint('usuario_id', name=op.f('verificaciones_identidad_usuario_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index('uq_verificacion_documento_aprobado', table_name='verificacion_identidad', postgresql_where=sa.text("resultado = 'aprobado'"))
    op.drop_index(op.f('ix_verificacion_identidad_usuario_id'), table_name='verificacion_identidad')
    op.drop_table('verificacion_identidad')
    op.drop_table('parametro_sistema')
    op.execute("DROP TYPE IF EXISTS resultado_verificacion")
    # ### end Alembic commands ###
